### ISSUE TITLE
Driver - Basic Values not saved

### ISSUE THREAD

**Issue by haooken** [adammhaile/PixelWeb#1]
LED Type
Channel Order
Gamma

Values not saved/loaded after server restart.

**Comment by adammhaile** [comment]
Just those? Are others saved?

**Comment by haooken** [comment]
Found one more not saved:
Controller -> Basic -> Rotation

I've verified that the following are also saved:
Basic -> #Pixels
Controller Type
Controller -> Basic -> Width, Height, Flip, Serpentine, and Threaded Update.

I haven't messed with the Driver -> Advanced settings.

**Comment by haooken** [comment]
Matrix rotation not saved.

**Comment by adammhaile** [comment]
Not seeing it... works here. Grab the latest and see if it still does it.

**Comment by haooken** [comment]
Yep, working now. Must have synced my local repo right before that change was committed.
