### ISSUE TITLE
Enhancement: Set all the leds to zero when stopping an animation

### ISSUE THREAD

**Issue by jimnet2005** [adammhaile/PixelWeb#9]
If possible, it would be great if all the leds are set to OFF when an animation is stopped or please provide a suggestion of how to do this by using the rest API (e.g. by creating an OFF/NULL animation?)

**Comment by adammhaile** [comment]
added in the cleanup methods in BaseAnimation. When the anim thread is killed by PW, it should blank out the display. Note, this may not always work if using threadedUpdate=True.
